# Copyright (c) 2024, Tomasz Bursztyka
#
# SPDX-License-Identifier: Apache-2.0

init:
  sync_rtc_setup:
    dependencies:
      - k_sys_work_q_init

  k_sys_work_q_init:
    dependencies:
      - mbox
